name: AniList readme workflow
on:
  schedule:
    # Runs at 2AM
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: AniList readme workflow
        uses: pxseu/anilist-readme@senpai
        with:
          user_id: 7575423
          timezone: "Asia/Dhaka"
          max_post_count: 50
          preferred_language: english
          date_format: "{h}:{m} {D} {MW} {Y}"
          
          
